# Generated by Django 2.2.6 on 2019-12-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
