# Generated by Django 2.2.6 on 2019-12-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_key',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
